// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import UpsertPauseStatusReducer from "../upsert_pause_status_reducer";

export type UpsertPauseStatusParams = __Infer<typeof UpsertPauseStatusReducer>;

