// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const PauseStatus = __t.object("PauseStatus", {
  sessionId: __t.string(),
  state: __t.string(),
  friendReply: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type PauseStatus = __Infer<typeof PauseStatus>;

